Update aceropaidscript

diff --git a/aceropaidscript b/aceropaidscript
--- a/aceropaidscript
+++ b/aceropaidscript
@@ -1,38 +1,35 @@
 #!/bin/bash
 
-## Copyright ©AceroVpnOwner
+## Copyright ©UDPTeam
 
-## Discord: https://discord.gg/civ3
+## Discord: [URL]https://discord.gg/civ3[/URL]
 
-## Script to keep-alive your DNSTT server domain record query from target resolver/local dns server
+## Script to keep-alive your DNSTT server domain record query from target resolver/local DNS server
 
 ## Run this script excluded from your VPN tunnel (split VPN tunneling mode)
 
-## run command: ./globe-James.sh l
+## Run command: ./globe-james.sh l
 
 ## Repeat dig command loop time (seconds) (positive integer only)
 
-LOOP_DELAY=5
+LOOP_DELAY=1  # Set the loop delay to 1 second
 
-## Define the aligned nameservers and hosts
+## Your DNSTT Nameserver & your Domain `A` Record
 
-declare -A SERVERS=(
-    ["in.plastik.palaboy.tech"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.bakal.palaboy.tech"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["jp.vannesa.palaboy.tech"]="124.6.181.4 124.6.181.36 112.198.115.44 112.198.111.92 112.198.115.36 112.198.115.60 124.6.181.12 124.6.181.44 124.6.181.20 gtm.palaboy.tech 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["hp.bisiro.palaboy.tech"]="124.6.181.4 124.6.181.36 112.198.115.44 112.198.111.92 112.198.115.36 112.198.115.60 124.6.181.12 124.6.181.44 124.6.181.20 gtm.palaboy.tech 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["us.bote.palaboy.tech"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.leonardo.palaboy.tech"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.jenny.lantindns.tech"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.jerald.acerodns.xyz"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
+NS='ns.dnstt.palaboy.tech'
+NS1='ns.dnstt.palaboy.tech'
+NS2='ns.dnstt.palaboy.tech'
+NS3='digi2.xd.teamwork-vpn.cloud'
+NS4='ns.dnsttpremium.acerodns.xyz'
+NS5='ns.paid.acerodns.xyz'
+NS6='ns.dnstt01contabo.acerodns.xyz'
+NS7='ns.dnsttcontabo.acerodns.xyz'
+A='ns.dnstt.palaboy.tech'
 
- ["ns.arnielvps.acerodns.xyz"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132. 10.10.10.1 10.0.0.001"
-["ns.dnsttpremium.acerodns.xyz"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.japandnstt.acerodns.xyz"]="124.6.181.4 124.6.181.36 112.198.115.44 112.198.111.92 112.198.115.36 112.198.115.60 124.6.181.12 124.6.181.44 124.6.181.20 gtm.palaboy.tech 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.kiratest.acerodns.xyz"]="124.6.181.4 124.6.181.36 112.198.115.44 112.198.111.92 112.198.115.36 112.198.115.60 124.6.181.12 124.6.181.44 124.6.181.20 gtm.palaboy.tech 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.paid.acerodns.xyz"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"
-    ["ns.noel.acerodns.xyz"]="124.6.181.4 124.6.181.36 124.6.181.12 121.54.70.166 121.54.70.132 10.10.10.1 10.0.0.001"   
-)
+## Add your DNS here
+
+declare -a HOSTS=('112.198.115.60' '124.6.181.12' '124.6.181.36' '112.198.115.44' '124.6.181.4' '124.6.181.44' '124.6.181.20')
+
 ## Linux' dig command executable filepath
 ## Select value: "CUSTOM|C" or "DEFAULT|D"
 
@@ -50,6 +47,11 @@ CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig
 
 VER=0.1
 
+# Define text color codes
+GREEN='\e[32m'
+RED='\e[31m'
+RESET='\e[0m'
+
 case "${DIG_EXEC}" in
 DEFAULT|D)
     _DIG="$(command -v dig)"
@@ -64,47 +66,30 @@ if [ ! $(command -v ${_DIG}) ]; then
     exit 1
 fi
 
-endscript() {
-    unset LOOP_DELAY SERVERS _DIG DIG_EXEC T R M
-    exit 1
-}
-
-trap endscript 2 15
-
+# Function to check DNS resolution and ping DNS nameservers
 check() {
-    for server in "${!SERVERS[@]}"; do
-        for host in ${SERVERS["$server"]}; do
-            T="${host}"
-            R="${server}"
-            
-            # Add ping and host lookup
-            ping -c 1 "${T}" &  # Ping the nameserver in the background
-            host "${R}" &  # Host lookup in the background
-            
-            timeout -k 3 3 ${_DIG} @${T} "${R}"  # Remove the domain name
-            if [ $? -eq 0 ]; then
-                M=32
-            else
-                M=31
-            fi
-            echo -e "\e[${M}m:${R} D:${T}\e[0m"
-        done
+    for host in "${HOSTS[@]}"; do
+        (timeout -k 3 3 ${_DIG} @"$host" "$A" && echo -e "${GREEN}Host $host: DNS resolution successful.${RESET}") || echo -e "${RED}Host $host: DNS resolution failed.${RESET}"
+    done
+
+    # Add DNS nameservers and host IPs to check with ping
+    PING_TARGETS=("$NS" "$NS1" "${HOSTS[@]}")
+
+    for target in "${PING_TARGETS[@]}"; do
+        if ping -c 1 -W 2 "$target" &>/dev/null; then
+            echo -e "${GREEN}Ping to $target: Success.${RESET}"
+        else
+            echo -e "${RED}Ping to $target: Failed.${RESET}"
+        fi
     done
 }
 
-echo "DNSTT Keep-Alive script <Discord @civ3>"
-echo "DNS List:"
-for server in "${!SERVERS[@]}"; do
-    echo -e "\e[34m${server}\e[0m -> ${SERVERS["$server"]}"
-done
+echo "DNSTT Keep-Alive script with DNS and host IP ping<Discord @civ3>"
+echo "DNS List: ${HOSTS[*]}"
 echo "CTRL + C to close script"
-
-if [ "${LOOP_DELAY}" -eq 1 ]; then
-    let "LOOP_DELAY++"
-fi
 
 while true; do
     check
-    echo '.--. .-.. . .- ... .     .-- .- .. -'
+    echo -ᴊαмαѕ σffι¢ιαℓ fяєєιиуєяиєт-
     sleep ${LOOP_DELAY}
 done
